// Checked through each source and its reachable private helpers; the gallery links each building block.
export const compositions = [
  {
    source: 'theme.tsx',
    families: ['settings'],
    primitives: ['Icon', 'RadioGroup', 'RadioGroupItem', 'RadioGroupIndicator', 'Text'],
  },
  {
    source: 'conversation.tsx',
    families: ['agent', 'agent-panel', 'voice'],
    primitives: [
      'AdaptivePanel',
      'AutoScrollArea',
      'Button',
      'Dock',
      'Form',
      'Heading',
      'Icon',
      'InputGroup',
      'InputGroupAddon',
      'InputGroupTextarea',
      'Link',
      'OptionStrip',
      'Prose',
      'ReadingColumn',
      'Row',
      'Stack',
      'Surface',
      'Text',
      'Toolbar',
    ],
  },
  {
    source: 'settings.tsx',
    families: ['settings'],
    primitives: [
      'Field',
      'FieldContent',
      'FieldDescription',
      'FieldLabel',
      'FieldTitle',
      'Heading',
      'Drawer',
      'Surface',
    ],
  },
] as const;
