// Checked against compiler-resolved JSX in these files; the gallery links each building block.
export const compositions = [
  {
    source: 'theme.tsx',
    families: ['settings'],
    primitives: ['Icon', 'RadioGroup', 'RadioGroupItem', 'RadioGroupIndicator', 'Text'],
  },
  {
    source: 'conversation.tsx',
    families: ['agent', 'agent-panel', 'voice'],
    primitives: [
      'AdaptivePanel',
      'AutoScrollArea',
      'Button',
      'Dock',
      'Heading',
      'Icon',
      'Link',
      'OptionStrip',
      'Prose',
      'ReadingColumn',
      'Row',
      'Stack',
      'StatusMark',
      'Surface',
      'Text',
      'Toolbar',
    ],
  },
  {
    source: 'settings.tsx',
    families: ['settings'],
    primitives: [
      'FeaturePage',
      'Field',
      'FieldContent',
      'FieldDescription',
      'FieldLabel',
      'Heading',
      'MenuSheet',
      'Stack',
      'Surface',
    ],
  },
  {
    source: 'sheet.tsx',
    families: ['settings', 'frames'],
    primitives: [
      'Button',
      'Drawer',
      'DrawerContent',
      'DrawerDescription',
      'DrawerHeader',
      'DrawerTitle',
      'Icon',
      'ScrollArea',
      'Stack',
    ],
  },
] as const;
